# Generated by Django 4.2.30 on 2026-09-12 19:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firebase_uid', models.CharField(db_index=True, help_text='Firebase Authentication UID — the link between Firebase and Django', max_length=128, unique=True)),
                ('email', models.EmailField(help_text='User email (synced from Firebase on login)', max_length=254, unique=True)),
                ('role', models.CharField(choices=[('economist', 'Economist/Statistician'), ('regulator', 'Regulator/Policy Analyst'), ('researcher', 'Researcher/Analyst')], db_index=True, default='researcher', help_text='Stakeholder role — determines default dashboard widget ordering', max_length=20)),
                ('display_name', models.CharField(blank=True, default='', help_text='Display name for UI personalization', max_length=100)),
                ('organization', models.CharField(blank=True, default='', help_text='Organization name (e.g., "MoSPI", "DGCA", "IIT Delhi")', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('dashboard_preferences', models.JSONField(blank=True, default=dict, help_text='UI preferences: theme, preferred_period, pinned_routes, etc.')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
