# Generated by Django 4.2.30 on 2026-09-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('economist', 'Economist/Statistician'), ('regulator', 'Regulator/Policy Analyst'), ('researcher', 'Researcher/Analyst'), ('custom', 'Custom Dashboard')], db_index=True, default='researcher', help_text='Stakeholder role — determines default dashboard widget ordering', max_length=20),
        ),
    ]
