# Generated by Django 6.1.1 on 2026-09-12 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index_date', models.DateField()),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('index_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sample_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawFare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('departure_date', models.DateField()),
                ('fare_raw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes_raw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CleanFare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('departure_date', models.DateField()),
                ('lead_time_days', models.IntegerField()),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_valid', models.BooleanField(default=True)),
                ('quality_flags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fares.rawfare')),
            ],
        ),
    ]
