# Generated by Django 4.2.30 on 2026-09-11 02:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawFare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(db_index=True, help_text='Data source identifier (e.g., "AirlineA", "OTA_X")', max_length=50)),
                ('origin', models.CharField(db_index=True, help_text='IATA airport code for origin (e.g., "DEL")', max_length=3)),
                ('destination', models.CharField(db_index=True, help_text='IATA airport code for destination (e.g., "BOM")', max_length=3)),
                ('departure_date', models.DateField(db_index=True, help_text='Scheduled departure date for this fare')),
                ('fare_raw', models.DecimalField(decimal_places=2, help_text='Base fare amount before taxes', max_digits=10)),
                ('taxes_raw', models.DecimalField(decimal_places=2, help_text='Tax/fee amount', max_digits=10)),
                ('currency', models.CharField(default='INR', help_text='ISO 4217 currency code', max_length=3)),
                ('scraped_at', models.DateTimeField(db_index=True, help_text='Timestamp when this fare was scraped/observed')),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Full raw response from the scraper for debugging')),
            ],
            options={
                'verbose_name': 'Raw Fare',
                'verbose_name_plural': 'Raw Fares',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['origin', 'destination', 'departure_date'], name='fares_rawfa_origin_468f37_idx'), models.Index(fields=['scraped_at'], name='fares_rawfa_scraped_9771c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index_date', models.DateField(db_index=True, help_text='Date (or period start date) for this index value')),
                ('route', models.CharField(blank=True, db_index=True, help_text='Route code (e.g., "DEL-BOM") or NULL for national aggregate', max_length=7, null=True)),
                ('index_value', models.DecimalField(decimal_places=2, help_text='Index value (base period = 100)', max_digits=8)),
                ('avg_fare', models.DecimalField(decimal_places=2, help_text='Average fare for this date/route/period', max_digits=10)),
                ('sample_size', models.IntegerField(help_text='Number of fare observations in this calculation')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, default='daily', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Price Index',
                'verbose_name_plural': 'Price Indices',
                'ordering': ['index_date'],
                'indexes': [models.Index(fields=['index_date', 'route', 'period_type'], name='fares_price_index_d_27be90_idx')],
                'unique_together': {('index_date', 'route', 'period_type')},
            },
        ),
        migrations.CreateModel(
            name='CleanFare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('origin', models.CharField(db_index=True, max_length=3)),
                ('destination', models.CharField(db_index=True, max_length=3)),
                ('departure_date', models.DateField(db_index=True)),
                ('lead_time_days', models.IntegerField(db_index=True, help_text='Days between scrape date and departure date')),
                ('total_fare', models.DecimalField(decimal_places=2, help_text='fare_raw + taxes_raw (total price paid)', max_digits=10)),
                ('is_valid', models.BooleanField(db_index=True, default=True, help_text='False if this record is a duplicate or corrupt')),
                ('quality_flags', models.JSONField(blank=True, default=list, help_text='List of quality/anomaly flags, e.g. ["price_outlier", "statistical_outlier"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_fare', models.OneToOneField(help_text='Link back to the original raw observation', on_delete=django.db.models.deletion.CASCADE, related_name='clean', to='fares.rawfare')),
            ],
            options={
                'verbose_name': 'Clean Fare',
                'verbose_name_plural': 'Clean Fares',
                'ordering': ['-departure_date'],
                'indexes': [models.Index(fields=['origin', 'destination', 'departure_date'], name='fares_clean_origin_d20392_idx'), models.Index(fields=['is_valid'], name='fares_clean_is_vali_800cf9_idx')],
            },
        ),
    ]
