# Generated by Django 4.2.30 on 2026-09-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(help_text='Auto-incremented model version number', unique=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True, help_text='When this model was trained')),
                ('record_count', models.IntegerField(help_text='Number of CleanFare records used for training')),
                ('parameters', models.JSONField(default=dict, help_text='Fitted model parameters (per-route stats, thresholds)')),
                ('metrics', models.JSONField(default=dict, help_text='Evaluation metrics (precision, recall, f1, accuracy)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this is the currently active model version')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this training run')),
            ],
            options={
                'verbose_name': 'Anomaly Model Version',
                'verbose_name_plural': 'Anomaly Model Versions',
                'ordering': ['-version'],
            },
        ),
    ]
