# Generated by Django 4.2.30 on 2026-09-12 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0002_anomalymodelversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarePrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route', models.CharField(db_index=True, help_text='Route code (e.g., "DEL-BOM")', max_length=7)),
                ('forecast_date', models.DateField(db_index=True, help_text='The date being forecasted')),
                ('predicted_value', models.DecimalField(decimal_places=2, help_text='Median forecast (50th percentile)', max_digits=10)),
                ('lower_bound', models.DecimalField(decimal_places=2, help_text='Lower bound (10th percentile — 80% prediction interval)', max_digits=10)),
                ('upper_bound', models.DecimalField(decimal_places=2, help_text='Upper bound (90th percentile — 80% prediction interval)', max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When this forecast was generated')),
                ('model_name', models.CharField(default='chronos-2', help_text='Name of the model that produced this forecast', max_length=100)),
            ],
            options={
                'verbose_name': 'Fare Prediction',
                'verbose_name_plural': 'Fare Predictions',
                'ordering': ['route', 'forecast_date'],
                'indexes': [models.Index(fields=['route', 'forecast_date'], name='fares_farep_route_16acb1_idx')],
                'unique_together': {('route', 'forecast_date', 'model_name')},
            },
        ),
    ]
