# Generated by Django 4.2.30 on 2026-09-12 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0003_fareprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentDataPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('dgca_traffic', 'DGCA Passenger Traffic'), ('dgca_avg_fare', 'DGCA Average Fare'), ('mospi_cpi', 'MoSPI CPI Index')], db_index=True, help_text='Data source identifier', max_length=50)),
                ('metric_name', models.CharField(db_index=True, help_text='Metric name (e.g., "passengers_carried", "avg_fare_inr", "cpi_transport")', max_length=100)),
                ('metric_value', models.DecimalField(decimal_places=2, help_text='Numeric value of the metric', max_digits=14)),
                ('period_start', models.DateField(db_index=True, help_text='Start date of the reporting period')),
                ('period_end', models.DateField(help_text='End date of the reporting period')),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('dimensions', models.JSONField(blank=True, default=dict, help_text='Contextual dimensions: {"airline": "IndiGo"}, {"route": "DEL-BOM"}, etc.')),
                ('fetched_at', models.DateTimeField(help_text='When this data point was fetched/loaded')),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Source metadata, includes {"fixture": true/false}')),
            ],
            options={
                'verbose_name': 'Government Data Point',
                'verbose_name_plural': 'Government Data Points',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['source', 'metric_name', 'period_start'], name='fares_gover_source_70b9b5_idx'), models.Index(fields=['period_start'], name='fares_gover_period__3d066d_idx')],
                'unique_together': {('source', 'metric_name', 'period_start', 'dimensions')},
            },
        ),
    ]
