# Generated by Django 4.2.30 on 2026-09-12 19:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0004_governmentdatapoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route', models.CharField(blank=True, db_index=True, help_text='Route code (e.g., "DEL-BOM") or NULL for national aggregate', max_length=7, null=True)),
                ('forecast_date', models.DateField(db_index=True, help_text='The date being forecasted')),
                ('predicted_index', models.DecimalField(decimal_places=2, help_text='Median forecast of the price index (50th percentile)', max_digits=8)),
                ('lower_bound', models.DecimalField(decimal_places=2, help_text='Lower bound (10th percentile — 80% prediction interval)', max_digits=8)),
                ('upper_bound', models.DecimalField(decimal_places=2, help_text='Upper bound (90th percentile — 80% prediction interval)', max_digits=8)),
                ('pct_change_from_latest', models.DecimalField(blank=True, decimal_places=2, help_text='Predicted percentage change from latest known index value', max_digits=6, null=True)),
                ('cpi_impact_note', models.TextField(blank=True, default='', help_text='Illustrative CPI impact note, e.g., "A projected 3.2% increase could contribute ~0.07 points to the CPI transport sub-index"')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When this forecast was generated')),
                ('model_name', models.CharField(default='chronos-2', help_text='Name of the model that produced this forecast', max_length=100)),
            ],
            options={
                'verbose_name': 'Index Forecast',
                'verbose_name_plural': 'Index Forecasts',
                'ordering': ['route', 'forecast_date'],
                'indexes': [models.Index(fields=['route', 'forecast_date'], name='fares_index_route_0ca021_idx')],
                'unique_together': {('route', 'forecast_date', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='ForecastAccuracyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route', models.CharField(blank=True, db_index=True, help_text='Route code or NULL for national aggregate', max_length=7, null=True)),
                ('forecast_date', models.DateField(db_index=True, help_text='The date that was forecasted')),
                ('predicted_index', models.DecimalField(decimal_places=2, help_text='The predicted index value', max_digits=8)),
                ('actual_index', models.DecimalField(blank=True, decimal_places=2, help_text='The actual index value (filled in after the date passes)', max_digits=8, null=True)),
                ('error', models.DecimalField(blank=True, decimal_places=2, help_text='Absolute error: |predicted - actual|', max_digits=8, null=True)),
                ('error_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage error: |predicted - actual| / actual × 100', max_digits=6, null=True)),
                ('within_interval', models.BooleanField(help_text='Whether the actual value fell within the prediction interval', null=True)),
                ('lower_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('generated_at', models.DateTimeField(help_text='When the prediction was generated')),
                ('evaluated_at', models.DateTimeField(blank=True, help_text='When the accuracy was evaluated (actual value filled in)', null=True)),
                ('model_name', models.CharField(default='chronos-2', max_length=100)),
            ],
            options={
                'verbose_name': 'Forecast Accuracy Log',
                'verbose_name_plural': 'Forecast Accuracy Logs',
                'ordering': ['-forecast_date'],
                'indexes': [models.Index(fields=['route', 'forecast_date'], name='fares_forec_route_20c5c8_idx'), models.Index(fields=['evaluated_at'], name='fares_forec_evaluat_12977a_idx')],
                'unique_together': {('route', 'forecast_date', 'model_name')},
            },
        ),
    ]
