# Generated by Django 4.2.30 on 2026-09-15 01:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0005_indexforecast_forecastaccuracylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBookingCurve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route', models.CharField(db_index=True, max_length=50)),
                ('airline', models.CharField(db_index=True, max_length=100)),
                ('flight_class', models.CharField(db_index=True, max_length=50)),
                ('days_left', models.IntegerField(db_index=True)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stops', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historical Booking Curve',
                'verbose_name_plural': 'Historical Booking Curves',
                'ordering': ['route', 'days_left'],
                'indexes': [models.Index(fields=['route', 'airline', 'flight_class', 'days_left'], name='fares_histo_route_ff434a_idx')],
                'unique_together': {('route', 'airline', 'flight_class', 'days_left', 'price')},
            },
        ),
    ]
