# Generated by Django 4.2.30 on 2026-09-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0006_historicalbookingcurve'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomalymodelversion',
            options={'ordering': ['-version', 'route'], 'verbose_name': 'Anomaly Model Version', 'verbose_name_plural': 'Anomaly Model Versions'},
        ),
        migrations.AddField(
            model_name='anomalymodelversion',
            name='contamination',
            field=models.FloatField(blank=True, help_text='Tuned contamination parameter', null=True),
        ),
        migrations.AddField(
            model_name='anomalymodelversion',
            name='model_blob',
            field=models.BinaryField(blank=True, help_text='Pickled PyOD model object', null=True),
        ),
        migrations.AddField(
            model_name='anomalymodelversion',
            name='route',
            field=models.CharField(blank=True, db_index=True, help_text='Route code (e.g., "DEL-BOM") or NULL for global', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='anomalymodelversion',
            name='version',
            field=models.IntegerField(help_text='Auto-incremented model version number (training run)'),
        ),
        migrations.AlterUniqueTogether(
            name='anomalymodelversion',
            unique_together={('version', 'route')},
        ),
    ]
