# Generated by Django 4.2.30 on 2026-09-14 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
                ('travel_date', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('empty', 'Empty'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('flight_code', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.CharField(max_length=20)),
                ('dep_time', models.CharField(max_length=20)),
                ('dep_city', models.CharField(blank=True, max_length=50, null=True)),
                ('arr_time', models.CharField(max_length=20)),
                ('arr_city', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(default='makemytrip_live', max_length=50)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='scrapers.scrapejob')),
            ],
        ),
    ]
