# Generated by Django 4.2.30 on 2026-09-15 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(help_text='Hashed version of the raw API key.', max_length=128, unique=True)),
                ('key_prefix', models.CharField(db_index=True, help_text='First 8 characters of the raw key, used for display/identification.', max_length=8)),
                ('role_scope', models.CharField(choices=[('economist', 'Economist/Statistician'), ('regulator', 'Regulator/Policy Analyst'), ('researcher', 'Researcher/Analyst'), ('custom', 'Custom Dashboard')], help_text="The role this key is scoped to (matches the owner's role).", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the key expires. If null, it never expires.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this key is active. Uncheck to revoke.')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=100, help_text='Maximum allowed requests per hour for this key.')),
                ('owner', models.ForeignKey(help_text='The user who generated and owns this key.', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiKeyUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_called', models.CharField(max_length=255)),
                ('called_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('response_status', models.PositiveIntegerField()),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='api_access.apikey')),
            ],
            options={
                'ordering': ['-called_at'],
            },
        ),
    ]
